name: build our image

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u masnasrinu --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag ghcr.io/masnasrinu/multiarch-example:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
